version: '3.8'

services:
  app:
    build: .
    container_name: keystone_app
    ports:
      - "9002:9002" # Next.js Admin UI
      - "4000:4000" # Genkit Inspector UI
      - "3400:3400" # Genkit Flows API
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - keystone_data:/usr/src/app/data
    # This command starts both the Next.js dev server and the Genkit server
    command: >
      sh -c "npm run genkit:dev & npm run dev"
    # For Windows Docker Desktop, this allows the container to access
    # services running on the host machine (like Ollama).
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  keystone_data:
