version: '3.8'

services:
  admin-ui:
    build: .
    container_name: keystone_admin_ui
    ports:
      - "9002:9002" # Next.js Admin UI
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - keystone_data:/usr/src/app/data
    environment:
      - KEYSTONE_MODE=admin
      - PORT=9002
    command: ["npm", "run", "dev"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api-proxy:
    build: .
    container_name: keystone_api_proxy
    ports:
      - "9003:9003" # API Proxy Server
      - "4000:4000" # Genkit Inspector UI (optional, could be on admin-ui)
      - "3400:3400" # Genkit Flows API (optional, could be on admin-ui)
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - keystone_data:/usr/src/app/data # Shared volume for API keys
    environment:
      - KEYSTONE_MODE=api
      - PORT=9003
    command: ["npm", "run", "start"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  keystone_data:
    driver: local
